#pragma once
#include <string>

namespace evgrpc {

// 32-hex-char correlation id for one RPC. Generated by `RpcScope` per RPC
// (one per handler invocation); service methods that need to log auth
// outcome with the same id (per spec §5.6) should call this FIRST, then
// pass the result to both the auth-logger call and `RpcScope`'s constructor.
//
// Not a real UUID (no version/variant bits) — just enough entropy for log
// correlation in a single process.
std::string NewReqId();

}  // namespace evgrpc